// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTANonCrown.Data.Context;

#nullable disable

namespace PTANonCrown.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429114435_PrimaryKey")]
    partial class PrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PTANonCrown.Data.Models.CoarseWoody", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_end")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_start")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Hardwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Softwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Unknown")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlotID");

                    b.ToTable("CoarseWoodys");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Plot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageSampleTreeAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageSampleTreeDBH_cm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageSampleTreeSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blowdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorizontalStructure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlanted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OGFSampleTreeAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OGFSampleTreeDBH_cm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OGFSampleTreeSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OneCohortSenescent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegenHeightHWLIT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegenHeightSWLIT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingBeechRegeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingLITSeedTree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingRegenCommercialSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingRegenLITSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnderstoryDominated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnderstoryStrata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UnevenAged")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("StandID");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.PlotTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("PlotTreatment");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Stand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CruiseID")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<int>("Ecodistrict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Organization")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Stands");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreatmentLookup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TreatmentLookup");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeDead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_end")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_start")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Hardwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Softwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Unknown")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlotID");

                    b.ToTable("TreesDead");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeLive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AGS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_cm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Diversity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HeightPredicted_m")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height_m")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LIT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Legacy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mast")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PLExSitu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PLInSitu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SCanopy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Species")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlotID");

                    b.ToTable("TreesLive");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.CoarseWoody", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotCoarseWoody")
                        .HasForeignKey("PlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Plot", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Stand", "Stand")
                        .WithMany("Plots")
                        .HasForeignKey("StandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.PlotTreatment", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotTreatments")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTANonCrown.Data.Models.TreatmentLookup", "Treatment")
                        .WithMany("PlotTreatments")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeDead", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotTreeDead")
                        .HasForeignKey("PlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeLive", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotTreeLive")
                        .HasForeignKey("PlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Plot", b =>
                {
                    b.Navigation("PlotCoarseWoody");

                    b.Navigation("PlotTreatments");

                    b.Navigation("PlotTreeDead");

                    b.Navigation("PlotTreeLive");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Stand", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreatmentLookup", b =>
                {
                    b.Navigation("PlotTreatments");
                });
#pragma warning restore 612, 618
        }
    }
}
