// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTANonCrown.Data.Context;

#nullable disable

namespace PTANonCrown.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PTANonCrown.Data.Models.CoarseWoody", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_end")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_start")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Hardwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Softwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Unknown")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlotID");

                    b.ToTable("CoarseWoodys");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Plot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageSampleTreeAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageSampleTreeDBH_cm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageSampleTreeSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blowdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorizontalStructure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlanted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OGFSampleTreeAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OGFSampleTreeDBH_cm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OGFSampleTreeSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OneCohortSenescent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantedType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegenHeightHWLIT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegenHeightSWLIT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingBeechRegeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingLITSeedTree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingRegenCommercialSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockingRegenLITSpecies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransectDirection")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TransectLength")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnderstoryDominated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnderstoryStrata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UnevenAged")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("StandID");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.PlotTreatment", b =>
                {
                    b.Property<int>("PlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotId", "TreatmentId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("PlotTreatments");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Stand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CruiseID")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<int>("Ecodistrict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Organization")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Stands");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Treatment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Planting"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Pre-commercial thinning"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Commercial thinning"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Strip shelterwood"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Patch shelterwood"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Uniform shelterwood"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Gap irregular shelterwood"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Continuous cover irregular shelterwood"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Single tree selection"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Group selection"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Partial harvest (unknown)"
                        });
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeDead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_end")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_start")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Hardwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Softwood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tally_Unknown")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlotID");

                    b.ToTable("TreesDead");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeLive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AGS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBH_cm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Diversity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HeightPredicted_m")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height_m")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LIT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Legacy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mast")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PLExSitu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PLInSitu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SCanopy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchSpecies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TreeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreeSpeciesID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlotID");

                    b.HasIndex("TreeSpeciesID");

                    b.ToTable("TreesLive");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeSpecies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardwoodSoftwood")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LIT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LIT_planted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TreeSpecies");

                    b.HasData(
                        new
                        {
                            ID = 999,
                            HardwoodSoftwood = 0,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Unknown",
                            ShortCode = "n/a"
                        },
                        new
                        {
                            ID = 1,
                            HardwoodSoftwood = 2,
                            LIT = true,
                            LIT_planted = true,
                            LT = true,
                            Name = "Red Spruce",
                            ShortCode = "rS"
                        },
                        new
                        {
                            ID = 2,
                            HardwoodSoftwood = 2,
                            LIT = true,
                            LIT_planted = true,
                            LT = true,
                            Name = "Eastern Hemlock",
                            ShortCode = "eH"
                        },
                        new
                        {
                            ID = 3,
                            HardwoodSoftwood = 2,
                            LIT = true,
                            LIT_planted = true,
                            LT = false,
                            Name = "White Pine",
                            ShortCode = "wP"
                        },
                        new
                        {
                            ID = 4,
                            HardwoodSoftwood = 2,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "White Spruce",
                            ShortCode = "wS"
                        },
                        new
                        {
                            ID = 5,
                            HardwoodSoftwood = 2,
                            LIT = true,
                            LIT_planted = true,
                            LT = false,
                            Name = "Black Spruce/Coastal",
                            ShortCode = "S"
                        },
                        new
                        {
                            ID = 6,
                            HardwoodSoftwood = 2,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Balsam Fir",
                            ShortCode = "bF"
                        },
                        new
                        {
                            ID = 7,
                            HardwoodSoftwood = 2,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Red Pine",
                            ShortCode = "rP"
                        },
                        new
                        {
                            ID = 8,
                            HardwoodSoftwood = 2,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Jack Pine",
                            ShortCode = "jP"
                        },
                        new
                        {
                            ID = 9,
                            HardwoodSoftwood = 2,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Eastern Larch",
                            ShortCode = "eL"
                        },
                        new
                        {
                            ID = 10,
                            HardwoodSoftwood = 1,
                            LIT = true,
                            LIT_planted = true,
                            LT = false,
                            Name = "Sugar Maple",
                            ShortCode = "sM"
                        },
                        new
                        {
                            ID = 11,
                            HardwoodSoftwood = 1,
                            LIT = true,
                            LIT_planted = true,
                            LT = false,
                            Name = "Yellow Birch",
                            ShortCode = "yB"
                        },
                        new
                        {
                            ID = 12,
                            HardwoodSoftwood = 1,
                            LIT = true,
                            LIT_planted = true,
                            LT = false,
                            Name = "White Ash",
                            ShortCode = "wA"
                        },
                        new
                        {
                            ID = 13,
                            HardwoodSoftwood = 1,
                            LIT = true,
                            LIT_planted = true,
                            LT = false,
                            Name = "Red Oak",
                            ShortCode = "rO"
                        },
                        new
                        {
                            ID = 14,
                            HardwoodSoftwood = 1,
                            LIT = true,
                            LIT_planted = false,
                            LT = true,
                            Name = "Red Maple",
                            ShortCode = "rM"
                        },
                        new
                        {
                            ID = 15,
                            HardwoodSoftwood = 1,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "White Birch",
                            ShortCode = "wB"
                        },
                        new
                        {
                            ID = 16,
                            HardwoodSoftwood = 1,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Trembling Aspen",
                            ShortCode = "tA"
                        },
                        new
                        {
                            ID = 17,
                            HardwoodSoftwood = 1,
                            LIT = false,
                            LIT_planted = false,
                            LT = false,
                            Name = "Large-tooth Aspen",
                            ShortCode = "lTA"
                        });
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.CoarseWoody", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotCoarseWoody")
                        .HasForeignKey("PlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Plot", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Stand", "Stand")
                        .WithMany("Plots")
                        .HasForeignKey("StandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.PlotTreatment", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotTreatments")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTANonCrown.Data.Models.Treatment", "Treatment")
                        .WithMany("PlotTreatments")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeDead", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotTreeDead")
                        .HasForeignKey("PlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeLive", b =>
                {
                    b.HasOne("PTANonCrown.Data.Models.Plot", "Plot")
                        .WithMany("PlotTreeLive")
                        .HasForeignKey("PlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTANonCrown.Data.Models.TreeSpecies", "TreeSpecies")
                        .WithMany("TreeLives")
                        .HasForeignKey("TreeSpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("TreeSpecies");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Plot", b =>
                {
                    b.Navigation("PlotCoarseWoody");

                    b.Navigation("PlotTreatments");

                    b.Navigation("PlotTreeDead");

                    b.Navigation("PlotTreeLive");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Stand", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.Treatment", b =>
                {
                    b.Navigation("PlotTreatments");
                });

            modelBuilder.Entity("PTANonCrown.Data.Models.TreeSpecies", b =>
                {
                    b.Navigation("TreeLives");
                });
#pragma warning restore 612, 618
        }
    }
}
